baseurl                  = "https://mikemc.cc"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Michael McLaren"
theme                    = "sam"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

# for blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # dateform             = "Mon Jan 02, 2006"
    # dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    dateform             = "2006 Jan 2 Mon"
    dateformfull         = "2006 Jan 2 Mon 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    # footerText           = "Call me Sam, a theme for Hugo."

# Metadata for Open Graph and Twitter
    description          = "Michael McLaren's personal website."               # Max 160 characters show in search results
    images               = ["screenshot.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Michael McLaren"

[[params.mainMenu]]
    link = "/about"
    text = "Michael McLaren"

[[params.mainMenu]]
    link = "/research"
    text = "research"

[[params.mainMenu]]
    link = "https://scholar.google.ca/citations?hl=en&user=rWErWm4AAAAJ&view_op=list_works&sortby=pubdate"
    text = "publications"
#     text = "writing"

[[params.mainMenu]]
    link = "https://mikemc.github.io/presentations"
    text = "talks"

[[params.mainMenu]]
    link = "/code"
    text = "code"

[imaging]
    quality = 75
